<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chương 8 Khảo sát kết cục nhị phân: Hồi quy logistic | Phân tích dữ liệu cho nghiên cứu hỗ trợ sinh sản bằng ngôn ngữ R</title>
  <meta name="description" content="Giáo trình thống kê chuyên dụng cho nghiên cứu hỗ trợ sinh sản" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Chương 8 Khảo sát kết cục nhị phân: Hồi quy logistic | Phân tích dữ liệu cho nghiên cứu hỗ trợ sinh sản bằng ngôn ngữ R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Giáo trình thống kê chuyên dụng cho nghiên cứu hỗ trợ sinh sản" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chương 8 Khảo sát kết cục nhị phân: Hồi quy logistic | Phân tích dữ liệu cho nghiên cứu hỗ trợ sinh sản bằng ngôn ngữ R" />
  
  <meta name="twitter:description" content="Giáo trình thống kê chuyên dụng cho nghiên cứu hỗ trợ sinh sản" />
  

<meta name="author" content="Lê Ngọc Khả Nhi và cộng sự" />


<meta name="date" content="2023-04-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"/>
<link rel="next" href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Thống kê chuyên dụng nghiên cứu IVF</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Lời giới thiệu</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#giới-thiệu-về-nghiên-cứu-hỗ-trợ-sinh-sản"><i class="fa fa-check"></i><b>1.1</b> Giới thiệu về nghiên cứu hỗ trợ sinh sản</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#đặt-vấn-đề"><i class="fa fa-check"></i><b>1.1.1</b> Đặt vấn đề</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#lịch-sử-nghiên-cứu-về-ivf"><i class="fa fa-check"></i><b>1.1.2</b> Lịch sử nghiên cứu về IVF</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#xu-hướng-nghiên-cứu-ivf"><i class="fa fa-check"></i><b>1.1.3</b> Xu hướng nghiên cứu IVF</a></li>
<li class="chapter" data-level="1.1.4" data-path="index.html"><a href="index.html#so-sánh-kết-quả-ivf-trước-và-sau-khi-có-nghiên-cứu"><i class="fa fa-check"></i><b>1.1.4</b> So sánh kết quả IVF trước và sau khi có nghiên cứu</a></li>
<li class="chapter" data-level="1.1.5" data-path="index.html"><a href="index.html#kết-luận"><i class="fa fa-check"></i><b>1.1.5</b> Kết luận</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#giới-thiệu-về-giáo-trình"><i class="fa fa-check"></i><b>1.2</b> Giới thiệu về giáo trình</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#ý-tưởng-về-một-giáo-trình-thống-kê-chuyên-dụng-cho-nghiên-cứu-htss"><i class="fa fa-check"></i><b>1.2.1</b> Ý tưởng về một giáo trình thống kê chuyên dụng cho nghiên cứu HTSS</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#mục-tiêu-học-tập"><i class="fa fa-check"></i><b>1.2.2</b> Mục tiêu học tập</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#nội-dung-và-quy-ước-trình-bày"><i class="fa fa-check"></i><b>1.2.3</b> Nội dung và quy ước trình bày</a></li>
<li class="chapter" data-level="1.2.4" data-path="index.html"><a href="index.html#nguồn-gốc-của-dữ-liệu"><i class="fa fa-check"></i><b>1.2.4</b> Nguồn gốc của dữ liệu</a></li>
<li class="chapter" data-level="1.2.5" data-path="index.html"><a href="index.html#về-một-số-thư-viện-r-quan-trọng"><i class="fa fa-check"></i><b>1.2.5</b> Về một số thư viện R quan trọng</a></li>
<li class="chapter" data-level="1.2.6" data-path="index.html"><a href="index.html#yêu-cầu-về-kiến-thức-và-kỹ-năng-cơ-bản"><i class="fa fa-check"></i><b>1.2.6</b> Yêu cầu về kiến thức và kỹ năng cơ bản</a></li>
<li class="chapter" data-level="1.2.7" data-path="index.html"><a href="index.html#khả-năng-tương-thích-với-chuyên-khoa-lâm-sàng-khác"><i class="fa fa-check"></i><b>1.2.7</b> Khả năng tương thích với chuyên khoa lâm sàng khác</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><i class="fa fa-check"></i><b>2</b> Khảo sát biến số liên tục: Mô hình hồi quy Gamma</a>
<ul>
<li class="chapter" data-level="2.1" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#giới-thiệu"><i class="fa fa-check"></i><b>2.1</b> Giới thiệu</a></li>
<li class="chapter" data-level="2.2" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#bối-cảnh-của-thí-nghiệm"><i class="fa fa-check"></i><b>2.2</b> Bối cảnh của thí nghiệm</a></li>
<li class="chapter" data-level="2.3" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#công-cụ-cần-thiết"><i class="fa fa-check"></i><b>2.3</b> Công cụ cần thiết</a></li>
<li class="chapter" data-level="2.4" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#chuẩn-bị-dữ-liệu"><i class="fa fa-check"></i><b>2.4</b> Chuẩn bị dữ liệu</a></li>
<li class="chapter" data-level="2.5" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#kế-hoạch-phân-tích"><i class="fa fa-check"></i><b>2.5</b> Kế hoạch phân tích</a></li>
<li class="chapter" data-level="2.6" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#phân-tích-mô-tả"><i class="fa fa-check"></i><b>2.6</b> Phân tích mô tả</a></li>
<li class="chapter" data-level="2.7" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#biện-luận-về-tính-phù-hợp-của-phân-phối-gamma"><i class="fa fa-check"></i><b>2.7</b> Biện luận về tính phù hợp của phân phối Gamma</a></li>
<li class="chapter" data-level="2.8" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#dựng-mô-hình-hồi-quy-với-phân-phối-gamma"><i class="fa fa-check"></i><b>2.8</b> Dựng mô hình hồi quy với phân phối Gamma</a></li>
<li class="chapter" data-level="2.9" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#suy-diễn-thống-kê-từ-mô-hình-glm-gamma"><i class="fa fa-check"></i><b>2.9</b> Suy diễn thống kê từ mô hình GLM-Gamma</a></li>
<li class="chapter" data-level="2.10" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#kết-luận-1"><i class="fa fa-check"></i><b>2.10</b> Kết luận</a></li>
<li class="chapter" data-level="2.11" data-path="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html"><a href="khảo-sát-biến-số-liên-tục-mô-hình-hồi-quy-gamma.html#thông-điệp-rút-gọn-làm-hành-trang"><i class="fa fa-check"></i><b>2.11</b> Thông điệp rút gọn làm hành trang</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><i class="fa fa-check"></i><b>3</b> Mô tả dữ liệu đa biến: Phân tích nhân tố chính (PCA)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#giới-thiệu-1"><i class="fa fa-check"></i><b>3.1</b> Giới thiệu</a></li>
<li class="chapter" data-level="3.2" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#bối-cảnh-của-thí-nghiệm-1"><i class="fa fa-check"></i><b>3.2</b> Bối cảnh của thí nghiệm</a></li>
<li class="chapter" data-level="3.3" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#công-cụ-cần-thiết-1"><i class="fa fa-check"></i><b>3.3</b> Công cụ cần thiết</a></li>
<li class="chapter" data-level="3.4" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#xác-định-số-thành-phần-chính-tối-ưu"><i class="fa fa-check"></i><b>3.4</b> Xác định số thành phần chính tối ưu</a></li>
<li class="chapter" data-level="3.5" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#phân-tích-pca"><i class="fa fa-check"></i><b>3.5</b> Phân tích PCA</a></li>
<li class="chapter" data-level="3.6" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#trình-bày-kết-quả-pca-bằng-biểu-đồ-biplot"><i class="fa fa-check"></i><b>3.6</b> Trình bày kết quả PCA bằng biểu đồ Biplot</a></li>
<li class="chapter" data-level="3.7" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#phân-tích-vai-trò-của-mỗi-biến-trong-2-thành-phần-chính"><i class="fa fa-check"></i><b>3.7</b> Phân tích vai trò của mỗi biến trong 2 thành phần chính</a></li>
<li class="chapter" data-level="3.8" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#khảo-sát-đặc-tính-phân-phối-của-mỗi-thành-phần-chính"><i class="fa fa-check"></i><b>3.8</b> Khảo sát đặc tính phân phối của mỗi thành phần chính</a></li>
<li class="chapter" data-level="3.9" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#kết-luận-2"><i class="fa fa-check"></i><b>3.9</b> Kết luận</a></li>
<li class="chapter" data-level="3.10" data-path="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html"><a href="mô-tả-dữ-liệu-đa-biến-phân-tích-nhân-tố-chính-pca.html#thông-điệp-rút-gọn-làm-hành-trang-1"><i class="fa fa-check"></i><b>3.10</b> Thông điệp rút gọn làm hành trang</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><i class="fa fa-check"></i><b>4</b> Khảo sát kết cục số đếm: Hồi quy Negative Binomial</a>
<ul>
<li class="chapter" data-level="4.1" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html#giới-thiệu-2"><i class="fa fa-check"></i><b>4.1</b> Giới thiệu</a></li>
<li class="chapter" data-level="4.2" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html#bối-cảnh-của-thí-nghiệm-2"><i class="fa fa-check"></i><b>4.2</b> Bối cảnh của thí nghiệm</a></li>
<li class="chapter" data-level="4.3" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html#kế-hoạch-phân-tích-1"><i class="fa fa-check"></i><b>4.3</b> Kế hoạch phân tích</a></li>
<li class="chapter" data-level="4.4" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html#công-cụ-cần-thiết-2"><i class="fa fa-check"></i><b>4.4</b> Công cụ cần thiết</a></li>
<li class="chapter" data-level="4.5" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html#thống-kê-mô-tả"><i class="fa fa-check"></i><b>4.5</b> Thống kê mô tả</a></li>
<li class="chapter" data-level="4.6" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html#biện-luận-về-tính-phù-hợp-của-quy-luật-phân-phối-nbi"><i class="fa fa-check"></i><b>4.6</b> Biện luận về tính phù hợp của quy luật phân phối NBI</a></li>
<li class="chapter" data-level="4.7" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html#phân-tích-hồi-quy-bằng-mô-hình-glm-nbi"><i class="fa fa-check"></i><b>4.7</b> Phân tích hồi quy bằng mô hình GLM NBI</a></li>
<li class="chapter" data-level="4.8" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html#diễn-đạt-kết-quả-phân-tích"><i class="fa fa-check"></i><b>4.8</b> Diễn đạt kết quả phân tích</a></li>
<li class="chapter" data-level="4.9" data-path="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html"><a href="khảo-sát-kết-cục-số-đếm-hồi-quy-negative-binomial.html#thông-điệp-rút-gọn-làm-hành-trang-2"><i class="fa fa-check"></i><b>4.9</b> Thông điệp rút gọn làm hành trang</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="phân-tích-mạng-lưới-tương-quan.html"><a href="phân-tích-mạng-lưới-tương-quan.html"><i class="fa fa-check"></i><b>5</b> Phân tích mạng lưới tương quan</a>
<ul>
<li class="chapter" data-level="5.1" data-path="phân-tích-mạng-lưới-tương-quan.html"><a href="phân-tích-mạng-lưới-tương-quan.html#giới-thiệu-3"><i class="fa fa-check"></i><b>5.1</b> Giới thiệu</a></li>
<li class="chapter" data-level="5.2" data-path="phân-tích-mạng-lưới-tương-quan.html"><a href="phân-tích-mạng-lưới-tương-quan.html#bối-cảnh-thí-nghiệm"><i class="fa fa-check"></i><b>5.2</b> Bối cảnh thí nghiệm</a></li>
<li class="chapter" data-level="5.3" data-path="phân-tích-mạng-lưới-tương-quan.html"><a href="phân-tích-mạng-lưới-tương-quan.html#thăm-dò-dữ-liệu"><i class="fa fa-check"></i><b>5.3</b> Thăm dò dữ liệu</a></li>
<li class="chapter" data-level="5.4" data-path="phân-tích-mạng-lưới-tương-quan.html"><a href="phân-tích-mạng-lưới-tương-quan.html#ma-trận-tương-quan"><i class="fa fa-check"></i><b>5.4</b> Ma trận tương quan</a></li>
<li class="chapter" data-level="5.5" data-path="phân-tích-mạng-lưới-tương-quan.html"><a href="phân-tích-mạng-lưới-tương-quan.html#sơ-đồ-mạng-lưới-tương-quan"><i class="fa fa-check"></i><b>5.5</b> Sơ đồ mạng lưới tương quan</a></li>
<li class="chapter" data-level="5.6" data-path="phân-tích-mạng-lưới-tương-quan.html"><a href="phân-tích-mạng-lưới-tương-quan.html#phân-tích-cấu-trúc-mạng-lưới-tương-quan"><i class="fa fa-check"></i><b>5.6</b> Phân tích cấu trúc mạng lưới tương quan</a></li>
<li class="chapter" data-level="5.7" data-path="phân-tích-mạng-lưới-tương-quan.html"><a href="phân-tích-mạng-lưới-tương-quan.html#yếu-tố-mỹ-thuật"><i class="fa fa-check"></i><b>5.7</b> Yếu tố mỹ thuật</a></li>
<li class="chapter" data-level="5.8" data-path="phân-tích-mạng-lưới-tương-quan.html"><a href="phân-tích-mạng-lưới-tương-quan.html#thông-điệp-rút-gọn-làm-hành-trang-3"><i class="fa fa-check"></i><b>5.8</b> Thông điệp rút gọn làm hành trang</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><i class="fa fa-check"></i><b>6</b> Khảo sát kết cục là tỷ lệ: Hồi quy Binomial</a>
<ul>
<li class="chapter" data-level="6.1" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html#giới-thiệu-4"><i class="fa fa-check"></i><b>6.1</b> Giới thiệu</a></li>
<li class="chapter" data-level="6.2" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html#bối-cảnh-của-thí-nghiệm-3"><i class="fa fa-check"></i><b>6.2</b> Bối cảnh của thí nghiệm</a></li>
<li class="chapter" data-level="6.3" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html#công-cụ-cần-thiết-cho-quy-trình"><i class="fa fa-check"></i><b>6.3</b> Công cụ cần thiết cho quy trình</a></li>
<li class="chapter" data-level="6.4" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html#chuẩn-bị-dữ-liệu-1"><i class="fa fa-check"></i><b>6.4</b> Chuẩn bị dữ liệu</a></li>
<li class="chapter" data-level="6.5" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html#kế-hoạch-phân-tích-2"><i class="fa fa-check"></i><b>6.5</b> Kế hoạch phân tích</a></li>
<li class="chapter" data-level="6.6" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html#thống-kê-mô-tả-1"><i class="fa fa-check"></i><b>6.6</b> Thống kê mô tả</a></li>
<li class="chapter" data-level="6.7" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html#dựng-mô-hình-hồi-quy-glm-binomial"><i class="fa fa-check"></i><b>6.7</b> Dựng mô hình hồi quy GLM Binomial</a></li>
<li class="chapter" data-level="6.8" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html#suy-diễn-thống-kê"><i class="fa fa-check"></i><b>6.8</b> Suy diễn thống kê</a></li>
<li class="chapter" data-level="6.9" data-path="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html"><a href="khảo-sát-kết-cục-là-tỷ-lệ-hồi-quy-binomial.html#thông-điệp-rút-gọn-làm-hành-trang-4"><i class="fa fa-check"></i><b>6.9</b> Thông điệp rút gọn làm hành trang</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><i class="fa fa-check"></i><b>7</b> Thí nghiệm khảo sát lặp lại: Mô hình GEE</a>
<ul>
<li class="chapter" data-level="7.1" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#giới-thiệu-5"><i class="fa fa-check"></i><b>7.1</b> Giới thiệu</a></li>
<li class="chapter" data-level="7.2" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#bối-cảnh-của-thí-nghiệm-4"><i class="fa fa-check"></i><b>7.2</b> Bối cảnh của thí nghiệm</a></li>
<li class="chapter" data-level="7.3" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#công-cụ-cho-quy-trình"><i class="fa fa-check"></i><b>7.3</b> Công cụ cho quy trình</a></li>
<li class="chapter" data-level="7.4" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#thống-kê-mô-tả-2"><i class="fa fa-check"></i><b>7.4</b> Thống kê mô tả</a></li>
<li class="chapter" data-level="7.5" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#phân-tích-bài-toán"><i class="fa fa-check"></i><b>7.5</b> Phân tích bài toán</a></li>
<li class="chapter" data-level="7.6" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#giới-thiệu-về-mô-hình-gee"><i class="fa fa-check"></i><b>7.6</b> Giới thiệu về mô hình GEE</a></li>
<li class="chapter" data-level="7.7" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#dựng-mô-hình-gee"><i class="fa fa-check"></i><b>7.7</b> Dựng mô hình GEE</a></li>
<li class="chapter" data-level="7.8" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#diễn-giải-kết-quả-mô-hình-gee"><i class="fa fa-check"></i><b>7.8</b> Diễn giải kết quả mô hình GEE</a></li>
<li class="chapter" data-level="7.9" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#diễn-đạt-kết-quả-của-phân-tích"><i class="fa fa-check"></i><b>7.9</b> Diễn đạt kết quả của phân tích:</a></li>
<li class="chapter" data-level="7.10" data-path="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html"><a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html#thông-điệp-rút-gọn-làm-hành-trang-5"><i class="fa fa-check"></i><b>7.10</b> Thông điệp rút gọn làm hành trang</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><i class="fa fa-check"></i><b>8</b> Khảo sát kết cục nhị phân: Hồi quy logistic</a>
<ul>
<li class="chapter" data-level="8.1" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#giới-thiệu-6"><i class="fa fa-check"></i><b>8.1</b> Giới thiệu</a></li>
<li class="chapter" data-level="8.2" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#bối-cảnh-của-thí-nghiệm-5"><i class="fa fa-check"></i><b>8.2</b> Bối cảnh của thí nghiệm</a></li>
<li class="chapter" data-level="8.3" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#kế-hoạch-phân-tích-3"><i class="fa fa-check"></i><b>8.3</b> Kế hoạch phân tích</a></li>
<li class="chapter" data-level="8.4" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#công-cụ-cần-thiết-cho-quy-trình-1"><i class="fa fa-check"></i><b>8.4</b> Công cụ cần thiết cho quy trình</a></li>
<li class="chapter" data-level="8.5" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#chuẩn-bị-dữ-liệu-2"><i class="fa fa-check"></i><b>8.5</b> Chuẩn bị dữ liệu</a></li>
<li class="chapter" data-level="8.6" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#phân-tích-mô-tả-1"><i class="fa fa-check"></i><b>8.6</b> Phân tích mô tả</a></li>
<li class="chapter" data-level="8.7" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#lý-thuyết-về-mô-hình-hồi-quy-logistic"><i class="fa fa-check"></i><b>8.7</b> Lý thuyết về mô hình hồi quy logistic</a></li>
<li class="chapter" data-level="8.8" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#mô-hình-hồi-quy-logistic-cho-biến-kết-quả-nhị-giá"><i class="fa fa-check"></i><b>8.8</b> Mô hình hồi quy Logistic cho biến kết quả nhị giá</a></li>
<li class="chapter" data-level="8.9" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#mô-hình-hồi-quy-binomial-cho-tỷ-lệ-optổng-số-phôi"><i class="fa fa-check"></i><b>8.9</b> Mô hình hồi quy Binomial cho tỷ lệ OP/tổng số phôi</a></li>
<li class="chapter" data-level="8.10" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#diễn-giải-kết-quả-của-phân-tích"><i class="fa fa-check"></i><b>8.10</b> Diễn giải kết quả của phân tích</a></li>
<li class="chapter" data-level="8.11" data-path="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html"><a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#thông-điệp-rút-gọn-làm-hành-trang-6"><i class="fa fa-check"></i><b>8.11</b> Thông điệp rút gọn làm hành trang</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><i class="fa fa-check"></i><b>9</b> Ứng dụng sơ đồ mạng định hướng không tuần hoàn (DAG)</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html#đặt-vấn-đề-1"><i class="fa fa-check"></i><b>9.1</b> Đặt vấn đề</a></li>
<li class="chapter" data-level="9.2" data-path="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html#bối-cảnh-của-thí-nghiệm-6"><i class="fa fa-check"></i><b>9.2</b> Bối cảnh của thí nghiệm</a></li>
<li class="chapter" data-level="9.3" data-path="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html#kế-hoạch-phân-tích-4"><i class="fa fa-check"></i><b>9.3</b> Kế hoạch phân tích</a></li>
<li class="chapter" data-level="9.4" data-path="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html#mô-tả-đơn-giản"><i class="fa fa-check"></i><b>9.4</b> Mô tả đơn giản</a></li>
<li class="chapter" data-level="9.5" data-path="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html#sơ-đồ-nhân-quả-và-mô-hình-dag"><i class="fa fa-check"></i><b>9.5</b> Sơ đồ nhân quả và mô hình DAG</a></li>
<li class="chapter" data-level="9.6" data-path="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html#xác-định-tập-hợp-biến-cần-hiệu-chỉnh"><i class="fa fa-check"></i><b>9.6</b> Xác định tập hợp biến cần hiệu chỉnh</a></li>
<li class="chapter" data-level="9.7" data-path="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html#ước-lượng-bằng-mô-hình-hồi-quy-logistic"><i class="fa fa-check"></i><b>9.7</b> Ước lượng bằng mô hình hồi quy logistic</a></li>
<li class="chapter" data-level="9.8" data-path="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html"><a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html#thông-điệp-rút-gọn-làm-hành-trang-7"><i class="fa fa-check"></i><b>9.8</b> Thông điệp rút gọn làm hành trang:</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html"><i class="fa fa-check"></i><b>10</b> Mô hình Machine learning khả diễn</a>
<ul>
<li class="chapter" data-level="10.1" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#giới-thiệu-7"><i class="fa fa-check"></i><b>10.1</b> Giới thiệu</a></li>
<li class="chapter" data-level="10.2" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#bối-cảnh-của-thí-nghiệm-7"><i class="fa fa-check"></i><b>10.2</b> Bối cảnh của thí nghiệm</a></li>
<li class="chapter" data-level="10.3" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#kế-hoạch-phân-tích-5"><i class="fa fa-check"></i><b>10.3</b> Kế hoạch phân tích:</a></li>
<li class="chapter" data-level="10.4" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#chuẩn-bị-và-thăm-dò-dữ-liệu"><i class="fa fa-check"></i><b>10.4</b> Chuẩn bị và thăm dò dữ liệu</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#các-thông-số-định-tính-rời-rạc"><i class="fa fa-check"></i><b>10.4.1</b> Các thông số định tính, rời rạc</a></li>
<li class="chapter" data-level="10.4.2" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#các-biến-số-liên-tục"><i class="fa fa-check"></i><b>10.4.2</b> Các biến số liên tục</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#phân-chia-dữ-liệu"><i class="fa fa-check"></i><b>10.5</b> Phân chia dữ liệu</a></li>
<li class="chapter" data-level="10.6" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#thiết-lập-mô-hình-phân-loại"><i class="fa fa-check"></i><b>10.6</b> Thiết lập mô hình phân loại</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#bước-3a-công-đoạn-sơ-chế-dữ-liệu"><i class="fa fa-check"></i><b>10.6.1</b> Bước 3a) Công đoạn sơ chế dữ liệu</a></li>
<li class="chapter" data-level="10.6.2" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#khởi-tạo-mô-hình-xgboost"><i class="fa fa-check"></i><b>10.6.2</b> Khởi tạo mô hình XGBoost</a></li>
<li class="chapter" data-level="10.6.3" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#tạo-workflow"><i class="fa fa-check"></i><b>10.6.3</b> Tạo workflow</a></li>
<li class="chapter" data-level="10.6.4" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#thực-hiện-kiểm-định-chéo-lặp-lại-10x10"><i class="fa fa-check"></i><b>10.6.4</b> Thực hiện kiểm định chéo lặp lại 10x10</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#các-tiêu-chí-hiệu-năng-mô-hình-phân-loại-nhị-phân"><i class="fa fa-check"></i><b>10.7</b> Các tiêu chí hiệu năng mô hình phân loại nhị phân</a></li>
<li class="chapter" data-level="10.8" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#huấn-luyện-mô-hình-trên-toàn-thể-dữ-liệu-tập-train"><i class="fa fa-check"></i><b>10.8</b> Huấn luyện mô hình trên toàn thể dữ liệu tập Train</a></li>
<li class="chapter" data-level="10.9" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#kiểm-định-độc-lập-hiệu-năng-mô-hình"><i class="fa fa-check"></i><b>10.9</b> Kiểm định độc lập hiệu năng mô hình</a></li>
<li class="chapter" data-level="10.10" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#phân-tích-hậu-kiểm-bằng-kỹ-thuật-shap"><i class="fa fa-check"></i><b>10.10</b> Phân tích hậu kiểm bằng kỹ thuật SHAP</a>
<ul>
<li class="chapter" data-level="10.10.1" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#giới-thiệu-về-phương-pháp-diễn-giải-mô-hình-shap"><i class="fa fa-check"></i><b>10.10.1</b> Giới thiệu về phương pháp diễn giải mô hình SHAP</a></li>
</ul></li>
<li class="chapter" data-level="10.11" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#vai-trò-của-các-thông-số-đóng-góp-vào-kết-quả-tiên-lượng"><i class="fa fa-check"></i><b>10.11</b> Vai trò của các thông số đóng góp vào kết quả tiên lượng</a>
<ul>
<li class="chapter" data-level="10.11.1" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#shap-score-có-thể-dùng-để-phân-cụm-dữ-liệu"><i class="fa fa-check"></i><b>10.11.1</b> SHAP score có thể dùng để phân cụm dữ liệu</a></li>
</ul></li>
<li class="chapter" data-level="10.12" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#bàn-luận"><i class="fa fa-check"></i><b>10.12</b> Bàn luận:</a>
<ul>
<li class="chapter" data-level="10.12.1" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#ưu-điểm-và-nhược-điểm-của-mô-hình-xgboost"><i class="fa fa-check"></i><b>10.12.1</b> Ưu điểm và nhược điểm của mô hình XGboost</a></li>
<li class="chapter" data-level="10.12.2" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#ưu-điểm-và-nhược-điểm-của-kỹ-thuật-shap"><i class="fa fa-check"></i><b>10.12.2</b> Ưu điểm và nhược điểm của kỹ thuật SHAP</a></li>
<li class="chapter" data-level="10.12.3" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#diễn-giải-cơ-chế-hoạt-động-của-mô-hình-ở-cấp-độ-cá-thể"><i class="fa fa-check"></i><b>10.12.3</b> Diễn giải cơ chế hoạt động của mô hình ở cấp độ cá thể:</a></li>
</ul></li>
<li class="chapter" data-level="10.13" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#kết-luận-3"><i class="fa fa-check"></i><b>10.13</b> Kết luận</a></li>
<li class="chapter" data-level="10.14" data-path="mô-hình-machine-learning-khả-diễn.html"><a href="mô-hình-machine-learning-khả-diễn.html#thông-điệp-rút-gọn-làm-hành-trang-8"><i class="fa fa-check"></i><b>10.14</b> Thông điệp rút gọn làm hành trang</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/kinokoberuji/OGStats" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Phân tích dữ liệu cho nghiên cứu hỗ trợ sinh sản bằng ngôn ngữ R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chương 8</span> Khảo sát kết cục nhị phân: Hồi quy logistic<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Biên soạn:</strong> Lê Ngọc Khả Nhi, Thân Trọng Thạch, Dương Thị Ngọc Châu</p>
<div id="giới-thiệu-6" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Giới thiệu<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#giới-thiệu-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ở chương này, chúng ta sẽ khảo sát thành quả được quan tâm nhất trong nghiên cứu về hỗ trợ sinh sản, đó là sự thụ thai (thai sinh hóa, lâm sàng), sự tiếp diễn thành công của thai kì (thai diễn tiến) và sự sinh nở. Trong y văn, những kết cục này thường được khảo sát như một giá trị mang tính nhị phân (Có hoặc không), hoặc tỷ lệ thành công trên tổng số cá thể bệnh nhân. Tuy nhiên, bản chất của loại kết cục này có thể được nhìn nhận như một xác suất hay khả năng thành công và cũng có tính kế thừa như một phần trong chuỗi kết quả của tiến trình thụ tinh nhân tạo. Vì vậy, ta có thể áp dụng quy luật phân phối nhị thức (binomial) để khảo sát chúng.</p>
<p>Thí dụ, kết quả thai diễn tiến thường được ghi nhận bằng 2 giá trị 0 (không) hoặc 1 (có) trong dữ liệu, nhưng bản chất của thai diễn tiến có thể xem như xác suất thành công <span class="math inline">\(p\)</span> của 1 thử nghiệm chuyển phôi. Chính vì trên thực tế, số lượng phôi được chuyển rất thấp, chỉ giới hạn ở 1 đến 2 phôi cho mỗi chu kì, nên kết quả quan sát được mới biểu hiện thành giá trị 0 hoặc 1.</p>
<p>Ta sẽ tìm hiểu về phân tích hồi quy logistic và trường hợp tổng quát của nó - một mô hình hồi quy GLM với phân phối Binomial, cho phép suy diễn thống kê cho kết quả nhị phân hoặc xác suất thành công của thử nghiệm.</p>
</div>
<div id="bối-cảnh-của-thí-nghiệm-5" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Bối cảnh của thí nghiệm<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#bối-cảnh-của-thí-nghiệm-5" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tình huống minh họa là một thử nghiệm lâm sàng với mục tiêu so sánh hiệu quả của phác đồ PPOS so với phác đồ tham chiếu là GnRH_ant đối với khả năng đạt được thai diễn tiến (ongoing pregnancy). Trong thí nghiệm này, phác đồ GnRH_ant được áp dụng cho nhóm đối chứng gồm 107 phụ nữ hiếm muộn, và phác đồ PPOS áp dụng cho nhóm can thiệp gồm 99 trường hợp. Sau khi thu hoạch noãn, thụ tinh và trữ phôi, người ta thực hiện từ 1 đến 3 lần chuyển phôi, mỗi lần 1-2 phôi và ghi nhận kết quả thai diễn tiến cộng dồn (nếu một trường hợp không thành công ở lần chuyển phôi đầu tiên, ta sẽ lặp lại quy trình chuyển phôi lần 2, hoặc lần 3). Thử nghiệm kết thúc ở lần thứ 3.</p>
<p>Kết cục sẽ được khảo sát dưới 3 hình thức:</p>
<ol style="list-style-type: decimal">
<li><p>Giá trị nhị phân: thành công hay thất bại tuyệt đối : có đạt được thai diễn tiến hay không (cho tối đa 3 lần): 0 = Không, 1 = Có (bất kể song thai, đơn thai)</p></li>
<li><p>Tần suất: số lượng thai diễn tiến cho mỗi cá thể (giá trị = 0 (không đạt được), 1 = đơn thai diễn tiến, 2 = song thai diễn tiến).</p></li>
<li><p>Tỷ lệ đạt thai diễn tiến = số thai diễn tiến chia cho tổng số phôi được chuyển. Thí dụ: Lần 1 chuyển 2 phôi, kết quả không đạt, lần 2 chuyển 2 phôi và đạt đơn thai, thì tỷ lệ thành công = <span class="math inline">\(1/(2+2) = 0.25\)</span></p></li>
</ol>
<p>Lưu ý rằng các trường hợp: sẫy thai, thai ngoài tử cung… xem như thất bại.</p>
</div>
<div id="kế-hoạch-phân-tích-3" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Kế hoạch phân tích<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#kế-hoạch-phân-tích-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Xác suất đạt thai diễn tiến cộng dồn khi áp dụng phác đồ PPOS, so với phương pháp tham chiếu là GnRH_ant sẽ được ước lượng bằng marginal Odds-ratio (OR) và risk-ratio (RR), có hiệu chỉnh cho Tuổi, AFC và độ dày nội mạc trung bình ngày chuyển phôi, dựa vào một mô hình hồi quy logistic. Suy diễn thống kê dựa vào phủ nhận giả thuyết vô hiệu (OR và RR = 1) ở ngưỡng ý nghĩa p = 0.05.</p>
</div>
<div id="công-cụ-cần-thiết-cho-quy-trình-1" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Công cụ cần thiết cho quy trình<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#công-cụ-cần-thiết-cho-quy-trình-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Thư viện dplyr trong hệ sinh thái tidyverse để thao tác dữ liệu và thống kê mô tả</p></li>
<li><p>Thư viện ggplot2, ggrides, tidybayes và ggdist để vẽ một số biểu đồ thống kê;</p></li>
<li><p>Thư viện patchwork để ghép nhiều biểu đồ ggplot2 với nhau.</p></li>
<li><p>Thư viện gamlss để dựng mô hình GLM với phân phối Binomial</p></li>
<li><p>Thư viện marginaleffects để ước tính OR, RR và suy diễn thống kê từ kết quả mô hình.</p></li>
</ul>
</div>
<div id="chuẩn-bị-dữ-liệu-2" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Chuẩn bị dữ liệu<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#chuẩn-bị-dữ-liệu-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Đầu tiên, ta tải dữ liệu từ file ‘PPOS_OP.csv’ vào dataframe df, sau đó ta</p>
<p>Trong dữ liệu này:</p>
<p>Age = Tuổi bệnh nhân,</p>
<p>AFC = Dự trữ buồng trứng cơ bản;</p>
<p>Thickness = độ dày nội mạc tử cung;</p>
<p>n_ET: tổng số phôi đã chuyển trong tiến trình nghiên cứu;</p>
<p>OP_cum = tần suất thai diễn tiến cộng dồn (giá trị cao nhất = 2, thấp nhất = 0);</p>
<p>OP_bin = kết quả thành công/thất bại tuyệt đối (2 giá trị 0,1)</p>
<p>OP_rate = tỷ lệ thai diễn tiến = OP_cum / n_ET</p>
</div>
<div id="phân-tích-mô-tả-1" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Phân tích mô tả<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#phân-tích-mô-tả-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ta kết hợp hàm group_by và summarize của thư viện dplyr để thực hiện thống kê mô tả cho những hình thức khác nhau của kết cục thai diễn tiến cộng dồn:</p>
<p><strong>a) Khảo sát tần suất thai diễn tiến (biến OP_cum)</strong></p>
<p>Đây là một biến số rời rạc và chỉ có thể có 3 giá trị: 0, 1 hoặc 2. Kết quả mô tả như sau:</p>
<p>Theo kết quả này, nếu xét về số lượng tuyệt đối, thì dường như giữa 2 phác đồ PPOS và GnRH không có sự khác biệt nào cả: Mode = 1 cho thấy kết quả thường gặp nhất cho cả 2 phác đồ là đạt ít nhất 1 thai diễn tiến. Xét bình quân thì nhóm PPOS có vẻ ưu thế hơn: số thai diễn tiến trung bình là 1.03 so với 0.81; cả 2 đều có độ phân tán cao tương đương (SD khoảng 0.7).</p>
<p><strong>b) Nếu xét về tỷ lệ thai diễn tiến trên tổng số phôi chuyển:</strong></p>
<p>Kết quả này cho thấy tỳ lệ thai diễn tiến trung bình có vẻ ưu thế hơn ở nhóm PPOS so với GnRHant: 0.46 so với 0.37 (nói cách khác, xác suất thụ thai thành công cho mỗi phôi chuyển có vẻ cao hơn ở phác đồ PPOS); Ta có thể ước tính Risk ratio (RR) giữa 2 phác đồ: <span class="math inline">\(RR = 0.457/0.37 = 1.235\)</span>. Tuy nhiên giá trị trung vị lại tương đương (0.5). Nói cách khác, nếu cứ chuyển phôi 2 lần thì dự kiến ít nhất sẽ có 1 lần đạt thành công.</p>
<p><strong>c) Tỷ số xác suất thành công/thất bại (Odds)</strong></p>
<p>Ta có thể ước lượng kết quả thai diễn tiến theo một cách khác, bằng tỷ số Odds</p>
<p><span class="math display">\[Odds = \frac{p_1}{p_0} = \frac{p_1}{(1 - p_1)}\]</span></p>
<p>Với <span class="math inline">\(p_1\)</span> là xác suất thành công, <span class="math inline">\(p_0\)</span> là xác suất thất bại.</p>
<p>Theo kết quả này, Odds của nhóm PPOS cao hơn Odds của nhóm GnRHant (0.556 so với 0.462), nói cách khác Odds ratio giữa PPOS và GnRHa : <span class="math inline">\(OR = 0.556/0.462 = 1.203\)</span></p>
<p><strong>d) Nếu xét giá trị thành công hay thất bại tuyệt đối (biến nhị giá OP_bin)</strong></p>
<p>Khi thực hiện phân tích này, đơn vị quan sát là cá thể bệnh nhân thay vì đơn vị phôi. Cách khảo sát này sẽ cho ra một kết quả khác</p>
<p>Dựa vào kết quả này, tỷ số xác suất thành công giữa 2 phác đồ : <span class="math inline">\(RR = 0.798/0.645 = 1.237\)</span> và Odds-ratio giữa chúng <span class="math inline">\(OR = 3.95/1.815 = 2.176\)</span>. Ở đây ta thấy một điểm thú vị là khi chọn đơn vị khảo sát là bệnh nhân, kết quả OR và RR có khuynh hướng cao hơn so với khi xét đơn vị khảo sát là phôi.</p>
<p>Ta lần lượt khảo sát trực quan 3 hình thức khảo sát kết quả thai diễn tiến trong 3 biểu đồ sau</p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p>Chú thích: Hình bên trái là biểu đồ cột chồng trình bày phân bố tỷ lệ Thành công/Thất bại (trục Y) giữa 2 phác đồ (trục X), hình bên phải gồm 2 biểu đồ: góc trên là biểu đồ tán xạ so sánh tần suất thai diễn tiến (trục Y) giữa 2 phác đồ (trục X), góc dưới là biểu đồ tần suất mô tả tỷ lệ thai diễn tiến cộng dồn (trục Y) giữa 2 phác đồ (trục X).</p>
<p>Ngoài 2 phác đồ, trong dữ liệu còn có một số hiệp biến khác như Tuổi, AFC và độ dày nội mạc có bản chất là biến số liên tục. Ta muốn khảo sát trực quan mối liên hệ giữa những hiệp biến này và xác suất đạt thai diễn tiến; ta có thể thực hiện theo 3 cách:</p>
<ol style="list-style-type: decimal">
<li><p>Liên hệ biến X và giá trị 0,1 của biến OP_bin, thông qua đồ thị của mô hình GLM với phân phối binomial (đồ thị hàm logistic)</p></li>
<li><p>Liên hệ biến X và giá trị tỷ lệ OP_rate, thông qua 1 mô hình hồi quy GLM với phân phối quasibinomial;</p></li>
<li><p>Liên hệ biến X và Odds, thông qua một mô hình hồi quy tuyến tính</p></li>
</ol>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-106-1.png" width="672" /></p>
<p>Chú thích: Hình trên gồm 3 cột, từ trái sang phải lần lượt trình bày: (1) Liên hệ giữa giá trị AFC, Age, Thickness (3 hàng, trục X) và khả năng đạt thai diễn tiến (trục Y); (2) Liên hệ giữa giá trị AFC, Age, Thickness (3 hàng, trục X) và Odds (tỉ số giữa xác suất thành công/thất bại); và (3) Liên hệ giữa giá trị AFC, Age, Thickness (3 hàng, trục X) và tỷ lệ thai diễn tiến trên tổng số phôi chuyển (trục Y). Dữ liệu được phân thành 2 nhóm: phác đồ PPOS (màu hồng) và GnRha (màu xanh).</p>
<p>Hình ảnh này gợi ý một số giả thuyết như sau:</p>
<ol style="list-style-type: decimal">
<li><p>AFC có hiệu ứng tương tác giữa AFC và loại phác đồ, vì 2 đồ thị các hàm tuyến tính/logistic của 2 nhóm cắt nhau, với hiệu ứng AFC khác biệt ở mỗi nhóm.</p></li>
<li><p>Tuổi có hiệu ứng độc lập và đồng nhất ở 2 phác đồ, khả năng thai diễn tiến tương quan nghịch với tuổi (giảm dần ở phụ nữ lớn tuổi);</p></li>
<li><p>Độ dày nội mạc tử cung có hiệu ứng độc lập với phác đồ, và đồng nhất giữa 2 nhóm phác đồ, hiệu ứng này rất yếu và có khuynh hướng tương quan thuận với khả năng thai diễn tiến.</p></li>
</ol>
</div>
<div id="lý-thuyết-về-mô-hình-hồi-quy-logistic" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> Lý thuyết về mô hình hồi quy logistic<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#lý-thuyết-về-mô-hình-hồi-quy-logistic" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cho bài toán thống kê hiện thời, ta cần một phương tiện cho phép liên kết giá trị của một biến độc lập (yếu tố tiên lượng) <span class="math inline">\(X\)</span> và một xác suất <span class="math inline">\(Y = p \in [0,1]\)</span>. Công cụ đó là mô hình logistic.</p>
<p>Mô hình hồi quy logistic có một lịch sử lâu đời (khoảng 78 năm), trước cả sự ra đời của lý thuyết về mô hình tuyến tính tổng quát GLM. Câu chuyện này khá dài, và sự khởi đầu của nó không liên quan gì đến xác suất và thống kê. Chúng ta sẽ khởi hành xa hơn từ chỗ nhận ra trong thế giới tự nhiên luôn hiện diện một quy luật tiến triển đặc biệt gồm 3 giai đoạn: 1) Giai đoạn sớm với sự tăng trưởng lũy tiến, xấp xỉ hàm mũ (exponential); 2) Tiếp theo là giai đoạn bão hòa: tốc độ phát triển chậm lại, tuyến tính; 3) Cuối cùng là giai đoạn ổn định và trưởng thành: sự phát triển ngừng lại. Khi biểu diễn tiến trình này theo thời gian, sẽ tạo ra một đường cong hình chữ S (sigmoid curve).</p>
<p>Ta có thể quan sát thấy quy luật này ở mọi lĩnh vực: tăng trưởng dân số/kinh tế, chu trình chuyển hóa sinh học, phản ứng hóa học. Trong Sản Phụ khoa, ta có thể nhìn thấy nó trong diễn tiến các hormone sinh dục, sự tăng trưởng của bào thai trong tử cung người mẹ, liên hệ liều / đáp ứng trong dược lực học…</p>
<p>Từ thế kỉ 18-19, những nhà toán học đã khảo sát quy luật này và lập ra các hàm toán học cho phép tái hiện đường cong hình chữ S, gọi là các hàm sigmoid, thí dụ hàm hyperbolic tangent của Jean Saurry năm 1774.</p>
<p>Trong số các hàm sigmoid, ta có hàm logistic là nhân vật chính trong câu chuyện này. Hàm logistic do nhà toán học người Pháp Pierre François Verhulst thiết lập vào năm 1845, với công dụng nguyên thủy nhằm khảo sát quy luật tăng trưởng dân số trong một quần thể. Công thức của hàm logistic được trình bày như sau.</p>
<p><span class="math display">\[y = \frac{e^{x}}{1 + e^{x}} = \frac{1}{1 + e^{-x}} = \frac{1}{2} + \frac{1}{2} tanh(\frac{x}{2})\]</span></p>
<p>Hình: đồ thị hàm logistic. Từ giá trị đầu vào là số thực <span class="math inline">\(x\)</span> bất kì, hàm logistic xuất kết quả là một giá trị trong khoảng (0,1).</p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-107-1.png" width="672" /></p>
<p>Một cách tình cờ, đặc tính này của hàm logistic dẫn đến một ứng dụng quan trọng trong lĩnh vực thống kê: nó giải quyết nhu cầu liên kết giá trị một tập biến <span class="math inline">\(X\)</span> và xác suất quan sát được giá trị <span class="math inline">\(Y=1\)</span> (Y là một biến nhị giá).</p>
<p>Mô hình logistic cổ điển được định nghĩa trực tiếp dựa vào hàm logistic, bằng cách thay đối số <span class="math inline">\(x\)</span> bằng một đại lượng <span class="math inline">\(g\)</span> như sau:</p>
<p><span class="math display">\[Pr(Y=1|X) \sim logistic(X) = \frac{1}{1 + e^{-g}}\]</span></p>
<p>Với <span class="math inline">\(g\)</span> là một biểu thức (hàm) tuyến tính được mô hình hóa theo tập biến <span class="math inline">\(X\)</span></p>
<p><span class="math display">\[g = \beta_0 + \beta_1X_1 + \beta_2X_2 + ... + \beta_jX_j\]</span>
Tuy nhiên, phiên bản thực dụng của mô hình hồi quy logistic chỉ được định hình vào năm 1944, khi nhà thống kê Joseph Berkson thiết lập một khái niệm quan trọng là Log odds và dùng nó làm thang đo cho bài toán ước lượng biến nhị giá.</p>
<p>Như ta biết, Odds là tỉ số giữa 2 xác suất. Với <span class="math inline">\(p\)</span> là xác suất thành công (<span class="math inline">\(Y=1\)</span>) và <span class="math inline">\(1-p\)</span> là xác suất thất bại (<span class="math inline">\(Y=0\)</span>), ta có:</p>
<p><span class="math display">\[Odds = \frac{p}{1-p}\]</span></p>
<p>Từ đó, ta có hàm logit là một công cụ khác cho phép liên kết trực tiếp tập biến <span class="math inline">\(X\)</span> và giá trị xác suất <span class="math inline">\(Y=p\)</span>. Hàm logit chính là sự áp dụng hàm logarit tự nhiên cho Odds:</p>
<p><span class="math display">\[logit(p) = log(\frac{p}{1-p})\]</span></p>
<p>Ta dễ dàng nhận thấy mối liên hệ nghịch đảo giữa 2 hàm logit và hàm logistic cổ điển:</p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-108-1.png" width="672" /></p>
<p>Từ đó, Berkson đã chuẩn hóa hồi quy logistic thành một phương pháp thống kê quy ước, sử dụng hàm logit thay vì logistic, và dùng log(odds) làm thang đo, đơn vị cho biến kết quả <span class="math inline">\(Y\)</span> trong mô hình. Sau đó, David Cox (1958) hoàn thiện kỹ thuật ước lượng tham số trong mô hình logistic.</p>
<p>Sau cùng, vào năm 1972 Nelder và Wedderburn đã hợp nhất mô hình logistic vào hệ thống mô hình hồi quy tuyến tính tổng quát (GLM), mô hình logistic là một thể đặc biệt của mô hình GLM, ước lượng giá trị của <span class="math inline">\(\mu\)</span> là trung bình của biến kết quả <span class="math inline">\(Y\)</span> theo quy luật phân phối Binomial và 2 tham số <span class="math inline">\(BI(n,\mu)\)</span></p>
<p><span class="math display">\[Pr(Y=y|n,\mu) = \frac{n!}{y!(n-y)!}\mu^{y}(1-p)^{n-y}\]</span></p>
<p>Ta ước lượng giá trị của <span class="math inline">\(\mu\)</span> bằng một mô hình tuyến tính với hàm liên kết logit:</p>
<p><span class="math display">\[logit(\mu) = log(\frac{\mu}{1-\mu}) \sim \beta_0 + \beta_1X_1 + \beta_2X_2 + ... + \beta_jX_j  \]</span>
Ta thấy, định nghĩa mô hình hồi quy logistic theo lý thuyết GLM và hàm logit dễ hiểu và đơn giản hơn nhiều so với định nghĩa nguyên thủy dựa vào hàm logistic. Nhưng vì lý do lịch sử, ta vẫn dùng tên gọi “logistic regression” cho loại mô hình này, nhưng ta hiểu bản chất của nó chỉ đơn giản là một mô hình GLM với phân phối Binomial hoặc Bernoulli (trường hợp đặc biệt khi <span class="math inline">\(n=1\)</span>)</p>
</div>
<div id="mô-hình-hồi-quy-logistic-cho-biến-kết-quả-nhị-giá" class="section level2 hasAnchor" number="8.8">
<h2><span class="header-section-number">8.8</span> Mô hình hồi quy Logistic cho biến kết quả nhị giá<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#mô-hình-hồi-quy-logistic-cho-biến-kết-quả-nhị-giá" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ta sẽ lần lượt phân tích 2 mô hình logistic khác nhau cho 2 biến kết quả: 1) kết quả nhị giá (thành công hoặc thất bại tuyệt đối về thai diễn tiến trong thí nghiệm, biến OP_bin) và 2) tỷ lệ thai diễn tiến trên tổng số phôi chuyển (biến OP_rate).</p>
<p>Cho kết quả thứ nhất, mô hình áp dụng một trường hợp đặc biệt của phân phối Binomial với <span class="math inline">\(n=1\)</span>, với đơn vị quan sát là cá thể bệnh nhân. Mục tiêu của mô hình là ước lượng xác suất quan sát được giá trị <span class="math inline">\(OP\_bin = 1\)</span> cho mỗi cá thể.</p>
<p>Mô hình có công thức: OP_bin ~ Protocol*AFC + Thickness + Age; family = “binomial” (hàm liên kết mặc định là logit).</p>
<p>Nội dung của mô hình như sau:</p>
<pre><code>## 
## Call:
## glm(formula = OP_bin ~ Protocol * AFC + Thickness + Age, family = &quot;binomial&quot;, 
##     data = df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2355  -0.9405   0.5561   0.7987   1.6910  
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)       2.28220    1.61373   1.414 0.157292    
## ProtocolPPOS      3.56952    1.02745   3.474 0.000512 ***
## AFC               0.14222    0.05030   2.828 0.004690 ** 
## Thickness         0.10929    0.07437   1.470 0.141679    
## Age              -0.14522    0.04414  -3.290 0.001001 ** 
## ProtocolPPOS:AFC -0.22953    0.07846  -2.925 0.003439 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 244.90  on 205  degrees of freedom
## Residual deviance: 215.36  on 200  degrees of freedom
## AIC: 227.36
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><strong>Diễn giải nội dung kết quả thô của mô hình:</strong></p>
<p>Do sử dụng hàm liên kết là logit, giá trị ước lượng của mô hình hiện thời là <span class="math inline">\(logit(\mu)\)</span> hay <span class="math inline">\(log(\frac{\mu}{1-\mu})\)</span> hay <span class="math inline">\(log(Odds)\)</span>, với <span class="math inline">\(\mu\)</span> là xác suất đạt thai diễn tiến trung bình (cho mổi cá thể). Tất cả hệ số hồi quy đang ở thang đo log(odds). Ta có thể chuyển về thang đo xác suất bằng hàm plogis, hoặc về thang đo Odds bằng hàm exponential.</p>
<p><span class="math inline">\(Intercept = 2.28220\)</span> tương ứng với log(odd) của xác suất thai diển tiến ở phác đồ tham chiếu (GnRH_ant), trong điều kiện giá trị Age, AFC và Thickness giữ cố định ở mức trung bình của quần thể.</p>
<p><span class="math inline">\(ProtocolPPOS = 3.56952\)</span> tương ứng với sự thay đổi log(odd) của xác suất thai diễn tiến ở phác đồ PPOS so với nhóm đối chứng (GnRH_ant), trong điều kiện giá trị Age, AFC và Thickness không đổi.</p>
<p>Các hệ số hối quy cho AFC,Age và Thickness lần lượt ứng với sự thay đổi của log(odd) xác suất thai diễn tiến khi AFC, Age hoặc Thickness tăng 1 đơn vị.</p>
<p>Vì mô hình có xét hiệu ứng tương tác giữa phác đồ PPOS và AFC, ta có thêm hệ số hồi quy ProtocolPPOS:AFC; với ý nghĩa đo lường sự thay đổi của log(odd) của xác suất thai diễn tiến khi AFC tăng 1 đơn vị và khi sử dụng phác đồ PPOS.</p>
<p>Một cách đơn giản, ta có thể xét dấu của các hệ số hồi quy này để hình dung về hiệu ứng mà các biến gây ra cho xác suất của thai diễn tiến. Một hệ số hồi quy &gt; 0 cho thấy mối tương quan thuận (làm tăng), ngược lại một hệ số hồi quy &lt;0 cho thấy tương quan nghịch (làm giảm).</p>
<p>Pr(&gt;|z|) trình bày giá trị p của kiểm định Wald, nhằm phủ nhận giả thuyết vô hiệu là một biến không gây ra hiệu ứng nào cả (không có liên hệ) đối với xac suất OP (hệ số hồi quy = 0).</p>
<p>Tuy nhiên, rất khó để thực hiện suy diễn thống kê theo cách này, nên ta sẽ theo con đường ước tính marginal effects (hiệu ứng cận biên) cho các yếu tố.</p>
<p>Giả định ta muốn khảo sát hiệu ứng của một biến định tính có 2 bậc giá trị (phác đồ PPOS hoặc GnRH), mô hình sẽ ước lượng được 2 giá trị xác suất thai diễn tiến trung bình cho 2 nhóm này là <span class="math inline">\(\mu_{PPOS}\)</span> và <span class="math inline">\(\mu_{GnRH}\)</span></p>
<p>Từ đây, ta có thể ước tính 3 loại marginal effects gồm:</p>
<p><strong>1) Marginal risk difference (RD)</strong></p>
<p>Trị số RD đo lường trực tiếp sự thay đổi/khác biệt/tương phản về xác suất giữa PPOS và phác đồ tham chiếu</p>
<p><span class="math display">\[RD = \mu_{PPOS} -  \mu_{GnRHant}\]</span>
RD cho biết khi dùng phác đồ PPOS, xác suất đạt thay diễn tiến sẽ thay đổi bao nhiêu so với phác đồ tham chiếu. Vì bản chất của RD là hiệu số giữa 2 xác suất, nó chỉ có thể dao động trong khoảng <span class="math inline">\([-1,1]\)</span>, RD = 0 cho thấy không có khác biệt (tính tương đương), RD &lt; 0 hoặc &gt; 0 cho phép xác định hiệu ứng của phác đồ nào cao hơn/thấp hơn.</p>
<p>Kết quả cho thấy: theo ước tính trung bình, nhóm bệnh nhân dùng phác đồ PPOS có xác suất thai diễn tiến tăng 0.148 (nói cách khác; tỷ lệ thai diễn tiến tăng 14.8%) so với phác đồ GnRH_ant, sự gia tăng này có ý nghĩa thống kê (khoảng tin cậy không chứa giá trị 0, p = 0.036).</p>
<p><strong>2) Marginal Odds ratio (OR)</strong></p>
<p>Trong phần trên, ta đã hiểu về bản chất của Odds là một tỷ số giữa 2 xác suất thành công/thất bại. Odds ratio là một cách để đo lường sự tương phản giữa 2 giá trị Odds tương ứng với 2 bậc giá trị của biến X (2 phác đồ), theo công thức sau:</p>
<p><span class="math display">\[OR = \frac{Odds_{PPOS}}{Odds_{GnRHa}} = \frac{\mu_{PPOS}/(1-\mu_{PPOS})}{\mu_{GnRHa}/(1-\mu_{GnRHa})}\]</span>
Vì là 1 tỷ số, OR có thể &gt;1, và dao động từ 0 đến <span class="math inline">\(+\infty\)</span>. Giá trị OR &lt; 1 cho thấy hiệu ứng của phác đồ PPOS thấp hơn so với nhóm tham chiếu, ngược lại OR &gt; 1 và càng lớn càng cho thấy phác đồ PPOS có hiệu quả cao hơn. OR = 1 cho thấy 2 phác đồ có hiệu ứng tương đương nhau.</p>
<p><strong>3) Marginal risk ratio (RR)</strong></p>
<p>Risk ở đây tương ứng với ý nghĩa xác suất, khả năng, tỷ lệ thành công (giá trị <span class="math inline">\(\mu\)</span> cho mỗi phác đồ), risk ratio đơn giản là tỷ số giữa 2 risks.</p>
<p><span class="math display">\[RR = \frac{\mu_{PPOS}}{\mu_{GnRHa}} \]</span>
RR được diễn giải tương tự như OR, giá trị RR=1 cho thấy 2 phác đồ là tương đương nhau, giá trị RR &gt; 1 cho thấy phác đồ PPOS có hiệu quả cao hơn, và ngược lại RR &lt; 1 cho thấy phác đồ GnRha có hiệu quả cao hơn.</p>
<p>Kết quả OR và RR được trình bày trong bảng sau:</p>
<p>Theo kết quả này, cả giá trị OR và RR đều cho thấy một hiệu quả ưu thế hơn của phác đồ PPOS so với GnRHa đối với khả năng đạt được thai diễn tiến. Sự chênh lệch về Odds và xác suất thành công giữa 2 phác đồ là có ý nghĩa thống kê.</p>
<p>Ta cũng có thể tính RD, OR và RR cho các biến định lượng, lúc này 2 bậc so sánh là <span class="math inline">\(X-1\)</span> và <span class="math inline">\(X+1\)</span>, kết quả cho biết hiệu ứng khi X gia tăng 1 đơn vị. Bảng sau đây trình bày giá trị RD, OR và RR cho Age, AFC, Thickness và cho riêng mỗi nhóm phác đồ.</p>
<p>Theo kết quả này, ta thấy AFC có tương quan thuận (OR &gt; 1 và RR &gt; 1) với xác suất thai diễn tiến, nhưng chỉ có ý nghĩa trong nhóm phác đồ GnRHa; Age có tương quan nghịch ý nghĩa với khả năng đạt thai diễn tiến cho cả 2 phác đồ (OR &lt; 1 và RR &lt; 1), trong khi không có liên hệ ý nghĩa nào giữa Thickness và khả năng đạt thai diễn tiến.</p>
<p>Thực ra, những trị số mà ta vừa ước lượng bao gồm RD, OR hoặc RR chỉ có ý nghĩa tóm tắt (abstraction) và cho biết thông tin về hiệu ứng ở mức độ quần thể. Hiện nay, có một số tác giả khuyến cáo về nhược điểm của việc chỉ báo cáo hiệu ứng cho biến nhị phân bằng một trị số duy nhất, và lợi ích của việc cung cấp thông tin chi tiết hơn về toàn thể đặc tính phân phối của hiệu ứng trong mẫu khảo sát.</p>
<p>Biểu đồ sau đây cho phép đối chiếu phân phối toàn thể của xác suất đạt thai diễn tiến cộng dồn trong 107 cá thể dùng phác đồ GnRHa và 99 cá thể dùng phác đồ PPOS.</p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-113-1.png" width="672" /></p>
<p>Chú thích: Hình trên trình bày 2 biểu đồ mật độ phân phối cho phép so sánh đặc điễm phân phối của xác suất thai diễn tiến (Trục X) giữa 2 phác đồ: GnRHa (màu xanh) và PPOS (màu hồng). 2 đường thẳng không liên tục tương ứng với giá trị trung vị của xác suất này ở mỗi nhóm.</p>
<p>Hình ảnh cho thấy có sự tương phản rõ nét giữa 2 phác đồ, với ưu thế nghiêng về phác đồ PPOS.</p>
<p>Một biểu đồ khác cho phép hình dung về cán cân chênh lệch của hiệu quả giữa 2 phác đồ, đến cấp độ từng cá thể.</p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-114-1.png" width="672" /></p>
<p>Chú thích: Đây là một biểu đồ tán xạ cho phép kiểm tra mức độ tương phản / chênh lệch giữa 2 phác đồ về xác suất thai diễn tiến. Trục X và Y trình bày 2 thang đo xác suất từ 0-1 cho mỗi phác đồ. Mỗi chấm tròn biểu thị cho một đơn vị khảo sát (cá thể bệnh nhân), đường phân giác của biểu đồ biểu thị cho giả thuyết là hai phác đồ tương đương hoàn toàn với nhau. Những điểm tròn nằm bên dưới đường phân giác này có hiệu quả GnRH_ant ưu thế hơn, trái lại với những điểm nằm bên trên đường này, phác đồ PPOS có hiệu ứng ưu thế hơn. Những điểm nằm rất gần và dọc theo đường này có hiệu quả tương đương giữa 2 phác đồ.</p>
<p>Các biểu đồ tiếp theo trình bày về mối liên hệ giữa Tuổi, AFC và Thickness với xác suất thai diễn tiến, riêng cho mỗi nhóm phác đồ:</p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-115-1.png" width="672" /></p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-116-1.png" width="672" /></p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-117-1.png" width="672" /></p>
</div>
<div id="mô-hình-hồi-quy-binomial-cho-tỷ-lệ-optổng-số-phôi" class="section level2 hasAnchor" number="8.9">
<h2><span class="header-section-number">8.9</span> Mô hình hồi quy Binomial cho tỷ lệ OP/tổng số phôi<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#mô-hình-hồi-quy-binomial-cho-tỷ-lệ-optổng-số-phôi" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Trong phần tiếp theo, ta sẽ phân tích loại kết quả thứ hai: tỷ lệ thai diễn tiến trên tổng số phôi đã chuyển (biến OP_cum).</p>
<p>Mô hình được dựng bằng thư viện gamlss với cú pháp giống như mô hình GLM Binomial trong chương trước. Công thức của mô hình như sau: “cbind(OP_cum, n_ET-OP_cum) ~ Protocol * AFC + Thickness + Age” (Nhắc lại: mô hình GLM Binomial tổng quát cần 2 biến ở vị trí kết quả: số kết quả thành công là biến OP_cum, và số kết quả thất bại, là hiệu số giữa số phôi chuyển và số thai)</p>
<p>tùy chỉnh family = BI(mu.link = “logit”) tương ứng với phân phối Binomial với hàm liên kết logit cho tham số <span class="math inline">\(\mu\)</span></p>
<p>Nội dung của mô hình này như sau:</p>
<pre><code>## GAMLSS-RS iteration 1: Global Deviance = 462.3237 
## GAMLSS-RS iteration 2: Global Deviance = 462.3237</code></pre>
<pre><code>## ******************************************************************
## Family:  c(&quot;BI&quot;, &quot;Binomial&quot;) 
## 
## Call:  gamlss(formula = cbind(OP_cum, n_ET - OP_cum) ~ Protocol *  
##     AFC + Thickness + Age, family = BI(mu.link = &quot;logit&quot;),      data = df) 
## 
## Fitting method: RS() 
## 
## ------------------------------------------------------------------
## Mu link function:  logit
## Mu Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)       0.16961    0.90175   0.188   0.8510  
## ProtocolPPOS      1.39994    0.54026   2.591   0.0103 *
## AFC               0.02922    0.02724   1.073   0.2846  
## Thickness         0.04225    0.03605   1.172   0.2426  
## Age              -0.05824    0.02403  -2.423   0.0163 *
## ProtocolPPOS:AFC -0.08438    0.04027  -2.096   0.0374 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## ------------------------------------------------------------------
## No. of observations in the fit:  206 
## Degrees of Freedom for the fit:  6
##       Residual Deg. of Freedom:  200 
##                       at cycle:  2 
##  
## Global Deviance:     462.3237 
##             AIC:     474.3237 
##             SBC:     494.2909 
## ******************************************************************</code></pre>
<p>Cách thức diễn giải mô hình này hoàn toàn giống như mô hình logistic ở trên nên ta không cần nhắc lại ở đây. Ta sẽ đi thẳng đến công đoạn ước tính 3 trị số marginal effects cho phác đồ PPOS từ mô hình này:</p>
<p>Theo kết quả này, có liên hệ ý nghĩa giữa phác đồ PPOS và sự gia tăng của tỷ lệ thai diễn tiến cộng dồn. Cụ thể nhóm phác đồ PPOS có tỷ lệ thai diễn tiến cao hơn trung bình 8.37% (DR = 0.0837, KTC95%: 0.002 - 0.165, p=0.04). Tỷ số Odds (OR) và tỷ số nguy cơ (RR) lần lượt là 1.44 và 1.27 đều cao hơn 1 cho thấy hiệu quả ưu thế hơn của phác đồ PPOS, cả hai đều có ý nghĩa thống kê.</p>
<p>Ta thực hiện mô tả phân phối toàn thể của hiệu ứng này qua hai biểu đồ sau:</p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-120-1.png" width="672" />
Hình ảnh này cho thấy mặc dù phần trùng lặp giữa phân phối của xác suất thai diễn tiến ở 2 phác đồ là khá cao, vẫn có một bộ phận cá thể cho thấy hiệu quả ưu thế hơn của phác đồ PPOS, và giá trị trung vị của 2 phân phối cách nhau một khoảng gần bằng 0.1.</p>
<p>Tương tự, trên biểu đồ tương hợp về xác suất thai diễn tiến ở 2 phác đồ, phần lớn cá thể nằm ở vị trí phía trên đường phân giác, cho thấy sự chênh lệch về ưu thế nghiêng về phía phác đồ PPOS.</p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-121-1.png" width="672" /></p>
<p>Cuối cùng, ta cũng khảo sát về liên hệ giữa Tuổi, AFC và Thickness với tỷ lệ thai diễn tiến cộng dồn tùy theo phác đồ.</p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-122-1.png" width="672" /></p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-123-1.png" width="672" /></p>
<p><img src="statistics-ivf-research_files/figure-html/unnamed-chunk-124-1.png" width="672" /></p>
</div>
<div id="diễn-giải-kết-quả-của-phân-tích" class="section level2 hasAnchor" number="8.10">
<h2><span class="header-section-number">8.10</span> Diễn giải kết quả của phân tích<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#diễn-giải-kết-quả-của-phân-tích" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Phân tích dữ liệu này cho phép rút ra một số kết luận như sau:</p>
<ul>
<li><p>Khả năng đạt được thai diễn tiến có thể được khảo sát dưới nhiều hình thức: xác suất quan sát được một kết quả thành công (biến nhị giá 0,1) trên cá thể bệnh nhân, xác suất thành công cho mỗi đơn vị noãn - hay tỷ lệ thành công trên tổng số phôi được chuyền. Cách thức khảo sát có thể ảnh hưởng đến kết quả phân tích thống kê (trong trường hợp hiện thời, cả 2 cách khảo sát đều cho ra thông điệp tương đồng, tuy nhiên có sự khác biệt về giá trị OR, RR hoặc RD).</p></li>
<li><p>Dù khảo sát dưới hình thức nào, thì đều dẫn về công cụ chung là mô hình GLM với phân phối Binomial với 2 tham số <span class="math inline">\(n\)</span>,<span class="math inline">\(\mu\)</span>. Mô hình logistic cổ điển là trường hợp đặc biệt khi <span class="math inline">\(n=1\)</span>. Cách diễn giải và suy luận thống kê là như nhau cho cả 2 mô hình.</p></li>
<li><p>Mô hình logistic (hay GLM Binomial) cho phép suy luận thống kê về mối liên hệ giữa 1 biến độc lập và một kết quả xác suất. Ta có thể áp dụng mô hình này cho những kết cục lâm sàng nhị phân, hoặc tỷ lệ.</p></li>
</ul>
</div>
<div id="thông-điệp-rút-gọn-làm-hành-trang-6" class="section level2 hasAnchor" number="8.11">
<h2><span class="header-section-number">8.11</span> Thông điệp rút gọn làm hành trang<a href="khảo-sát-kết-cục-nhị-phân-hồi-quy-logistic.html#thông-điệp-rút-gọn-làm-hành-trang-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Trong quy trình thụ tinh nhân tạo, tuy có nhiều loại kết cục lâm sàng khác nhau nhưng chuỗi kết cục này đều có thể quy về cùng một khái niệm đó là khả năng (xác suất) thành công tương ứng với mỗi công đoạn.</p></li>
<li><p>Khi đã nhận ra bản chất này, ta sẽ thấy mô hình tuyến tính tổng quát với phân phối nhị thức (và dạng đặc biệt của nó là hồi quy logistic) là công cụ thống kê quan trọng nhất trong nghiên cứu hỗ trợ sinh sản, nó cho phép suy luận thống kê cho toàn bộ chuỗi kết cục kể từ sau công đoạn lấy noãn, bao gồm khả năng thụ tinh, tạo phôi, thụ thai, và sinh nở thành công.</p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="thí-nghiệm-khảo-sát-lặp-lại-mô-hình-gee.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ứng-dụng-sơ-đồ-mạng-định-hướng-không-tuần-hoàn-dag.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/kinokoberuji/OGStats/edit/master/07-Logistic.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["statistics-ivf-research.pdf", "statistics-ivf-research.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
